server:
  port: 9595

spring:
  application:
    name: Bank
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  graphql:
    enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 1

grpc:
  client:
    BankingService:
      address: static://localhost:9090
      negotiation-type: plaintext

springdoc:
  swagger-ui:
    enabled: true
    url: swagger.yaml
    try-it-out-enabled: false
    syntax-highlight:
      activated: true